---
- hosts: all
  become: true
  connection: ssh
  tasks:
  - name: Updating apt
    command: sudo apt-get update

  - name: Install Docker
    command: sudo apt-get install -y docker.io

  - name: Start Docker Service
    command: sudo systemctl start docker

  - name: docker run user
    shell: usermod -aG docker ubuntu
    
  - name: Deploy Docker Container
    command: docker run -itd -p 8084:8081 ssah6694/insuranceimage:latest
